using System.Collections.Immutable;
using FilterTheSpire2.FilterTheSpire2Code.Characters;
using FilterTheSpire2.FilterTheSpire2Code.Helpers;
using MegaCrit.Sts2.Core.Entities.Cards;

namespace FilterTheSpire2.FilterTheSpire2Code.Cards;

// public enum CardRarity
// {
//     Common,
//     Uncommon,
//     Rare,
// }

public sealed record CardDefinition(
    CardOptions Card,
    CharacterOptions Character,
    CardRarity Rarity);

public static class CardRules
{
    private static readonly ImmutableArray<CardDefinition> AllCardDefinitions =
    [
        #region Ironclad pool

        new(CardOptions.Aggression, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Anger, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Armaments, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.AshenStrike, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Barricade, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Bash, CharacterOptions.Ironclad, CardRarity.Basic),
        new(CardOptions.BattleTrance, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.BloodWall, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Bloodletting, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Bludgeon, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.BodySlam, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Brand, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Break, CharacterOptions.Ironclad, CardRarity.Ancient),
        new(CardOptions.Breakthrough, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Bully, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.BurningPact, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Cascade, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Cinder, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Colossus, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Conflagration, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Corruption, CharacterOptions.Ironclad, CardRarity.Ancient),
        new(CardOptions.CrimsonMantle, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Cruelty, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.DarkEmbrace, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.DefendIronclad, CharacterOptions.Ironclad, CardRarity.Basic),
        new(CardOptions.DemonForm, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Dismantle, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Dominate, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.DrumOfBattle, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.EvilEye, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.ExpectAFight, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Feed, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.FeelNoPain, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.FiendFire, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.FightMe, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.FlameBarrier, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.ForgottenRitual, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Havoc, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Headbutt, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Hellraiser, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Hemokinesis, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.HowlFromBeyond, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Impervious, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.InfernalBlade, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Inferno, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Inflame, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.IronWave, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Juggernaut, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Juggling, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Mangle, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.MoltenFist, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.NotYet, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Offering, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.OneTwoPunch, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.PactsEnd, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.PerfectedStrike, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Pillage, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.PommelStrike, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.PrimalForce, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Pyre, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Rage, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Rampage, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Rupture, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.SecondWind, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.SetupStrike, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.ShrugItOff, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Spite, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Stampede, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Stoke, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Stomp, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.StoneArmor, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.StrikeIronclad, CharacterOptions.Ironclad, CardRarity.Basic),
        new(CardOptions.SwordBoomerang, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Taunt, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.TearAsunder, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Thrash, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Thunderclap, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Tremble, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.TrueGrit, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.TwinStrike, CharacterOptions.Ironclad, CardRarity.Common),
        new(CardOptions.Unmovable, CharacterOptions.Ironclad, CardRarity.Rare),
        new(CardOptions.Unrelenting, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Uppercut, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Vicious, CharacterOptions.Ironclad, CardRarity.Uncommon),
        new(CardOptions.Whirlwind, CharacterOptions.Ironclad, CardRarity.Uncommon),

        #endregion

        #region Silent pool

        new(CardOptions.Abrasive, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Accelerant, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Accuracy, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.Acrobatics, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.Adrenaline, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Afterimage, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Anticipate, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.Assassinate, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Backflip, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.Backstab, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.BladeOfInk, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.BladeDance, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.Blur, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.BouncingFlask, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.BubbleBubble, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.BulletTime, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Burst, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.CalculatedGamble, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.CloakAndDagger, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.CorrosiveWave, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.DaggerSpray, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.DaggerThrow, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.Dash, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.DeadlyPoison, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.DefendSilent, CharacterOptions.Silent, CardRarity.Basic),
        new(CardOptions.Deflect, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.DodgeAndRoll, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.EchoingSlash, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Envenom, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.EscapePlan, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.Expertise, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.Expose, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.FanOfKnives, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Finisher, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.Flechettes, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.FlickFlack, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.Scare, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.Footwork, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.GrandFinale, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.HandTrick, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.Haze, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.HiddenDaggers, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.InfiniteBlades, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.KnifeTrap, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.LeadingStrike, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.LegSweep, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.Malaise, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.MasterPlanner, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.MementoMori, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.Mirage, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.Murder, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Neutralize, CharacterOptions.Silent, CardRarity.Basic),
        new(CardOptions.Nightmare, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.NoxiousFumes, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.Outbreak, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.PhantomBlades, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.PiercingWail, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.Pinpoint, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.PoisonedStab, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.Pounce, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.PreciseCut, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.Predator, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.Prepared, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.Reflex, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.Ricochet, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.SerpentForm, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.ShadowStep, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Shadowmeld, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Skewer, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.Slice, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.Snakebite, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.Speedster, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.StormOfSteel, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Strangle, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.StrikeSilent, CharacterOptions.Silent, CardRarity.Basic),
        new(CardOptions.SuckerPunch, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.Suppress, CharacterOptions.Silent, CardRarity.Ancient),
        new(CardOptions.Survivor, CharacterOptions.Silent, CardRarity.Basic),
        new(CardOptions.Tactician, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.TheHunt, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.ToolsOfTheTrade, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Tracking, CharacterOptions.Silent, CardRarity.Rare),
        new(CardOptions.Untouchable, CharacterOptions.Silent, CardRarity.Common),
        new(CardOptions.UpMySleeve, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.WellLaidPlans, CharacterOptions.Silent, CardRarity.Uncommon),
        new(CardOptions.WraithForm, CharacterOptions.Silent, CardRarity.Ancient),

        #endregion

        #region Regent pool

        new(CardOptions.Alignment, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.Arsenal, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.AstralPulse, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.BeatIntoShape, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.Begone, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.BigBang, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.BlackHole, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.Bombardment, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.Bulwark, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.BundleOfJoy, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.CelestialMight, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.Charge, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.ChildOfTheStars, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.CloakOfStars, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.CollisionCourse, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.Comet, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.Conqueror, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.Convergence, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.CosmicIndifference, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.CrashLanding, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.CrescentSpear, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.CrushUnder, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.DecisionsDecisions, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.DefendRegent, CharacterOptions.Regent, CardRarity.Basic),
        new(CardOptions.Devastate, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.DyingStar, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.FallingStar, CharacterOptions.Regent, CardRarity.Basic),
        new(CardOptions.ForegoneConclusion, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.Furnace, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.GammaBlast, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.GatherLight, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.Genesis, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.Glimmer, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.Glitterstream, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.Glow, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.Guards, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.GuidingStar, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.HeavenlyDrill, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.Hegemony, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.HeirloomHammer, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.HiddenCache, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.IAmInvincible, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.KinglyKick, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.KinglyPunch, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.KnockoutBlow, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.KnowThyPlace, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.LunarBlast, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.MakeItSo, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.ManifestAuthority, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.MeteorShower, CharacterOptions.Regent, CardRarity.Ancient),
        new(CardOptions.MonarchsGaze, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.Monologue, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.NeutronAegis, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.Orbit, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.PaleBlueDot, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.Parry, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.ParticleWall, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.Patter, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.PhotonCut, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.PillarOfCreation, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.Prophesize, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.Quasar, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.Radiate, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.RefineBlade, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.Reflect, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.Resonance, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.RoyalGamble, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.Royalties, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.SeekingEdge, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.SevenStars, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.ShiningStrike, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.SolarStrike, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.SpectrumShift, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.SpoilsOfBattle, CharacterOptions.Regent, CardRarity.Common),
        new(CardOptions.Stardust, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.StrikeRegent, CharacterOptions.Regent, CardRarity.Basic),
        new(CardOptions.SummonForth, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.Supermassive, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.SwordSage, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.Terraforming, CharacterOptions.Regent, CardRarity.Uncommon),
        new(CardOptions.TheSealedThrone, CharacterOptions.Regent, CardRarity.Ancient),
        new(CardOptions.TheSmith, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.Tyranny, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.Venerate, CharacterOptions.Regent, CardRarity.Basic),
        new(CardOptions.VoidForm, CharacterOptions.Regent, CardRarity.Rare),
        new(CardOptions.WroughtInWar, CharacterOptions.Regent, CardRarity.Common),

        #endregion

        #region Necrobinder pool

        new(CardOptions.Afterlife, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.BansheesCry, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.BlightStrike, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.Bodyguard, CharacterOptions.Necrobinder, CardRarity.Basic),
        new(CardOptions.BoneShards, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.BorrowedTime, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Bury, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Calcify, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.CallOfTheVoid, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.CaptureSpirit, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Cleanse, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Countdown, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.DanseMacabre, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.DeathMarch, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Deathbringer, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.DeathsDoor, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Debilitate, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.DefendNecrobinder, CharacterOptions.Necrobinder, CardRarity.Basic),
        new(CardOptions.Defile, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.Defy, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.Delay, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Demesne, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.DevourLife, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Dirge, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.DrainPower, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.Dredge, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Eidolon, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.EndOfDays, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.EnfeeblingTouch, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Eradicate, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Fear, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.Fetch, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Flatten, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.ForbiddenGrimoire, CharacterOptions.Necrobinder, CardRarity.Ancient),
        new(CardOptions.Friendship, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.GraveWarden, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.Graveblast, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.Hang, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Haunt, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.HighFive, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Invoke, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.Lethality, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Melancholy, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Misery, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.NecroMastery, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.NegativePulse, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.Neurosurge, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.NoEscape, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Oblivion, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Pagestorm, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Parse, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Poke, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.Protector, CharacterOptions.Necrobinder, CardRarity.Ancient),
        new(CardOptions.PullAggro, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.PullFromBelow, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Putrefy, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Rattle, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Reanimate, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Reap, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.ReaperForm, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Reave, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.RightHandHand, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Sacrifice, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Scourge, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.SculptingStrike, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.Seance, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.SentryMode, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Severance, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.SharedFate, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Shroud, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.SicEm, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.SleightOfFlesh, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Snap, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.SoulStorm, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Sow, CharacterOptions.Necrobinder, CardRarity.Common),
        new(CardOptions.SpiritOfAsh, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Spur, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Squeeze, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.StrikeNecrobinder, CharacterOptions.Necrobinder, CardRarity.Basic),
        new(CardOptions.TheScythe, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.TimesUp, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Transfigure, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Undeath, CharacterOptions.Necrobinder, CardRarity.Rare),
        new(CardOptions.Unleash, CharacterOptions.Necrobinder, CardRarity.Basic),
        new(CardOptions.Veilpiercer, CharacterOptions.Necrobinder, CardRarity.Uncommon),
        new(CardOptions.Wisp, CharacterOptions.Necrobinder, CardRarity.Common),

        #endregion

        #region Defect pool

        new(CardOptions.AdaptiveStrike, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.AllForOne, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.BallLightning, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.Barrage, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.BeamCell, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.BiasedCognition, CharacterOptions.Defect, CardRarity.Ancient),
        new(CardOptions.BoostAway, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.BootSequence, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Buffer, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.BulkUp, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Capacitor, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Chaos, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.ChargeBattery, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.Chill, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Claw, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.ColdSnap, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.Compact, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.CompileDriver, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.ConsumingShadow, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Coolant, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Coolheaded, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.CreativeAi, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Darkness, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.DefendDefect, CharacterOptions.Defect, CardRarity.Basic),
        new(CardOptions.Defragment, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.DoubleEnergy, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Dualcast, CharacterOptions.Defect, CardRarity.Basic),
        new(CardOptions.EchoForm, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Feral, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.FightThrough, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.FlakCannon, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.FocusedStrike, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.Ftl, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Fusion, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.GeneticAlgorithm, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Glacier, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Glasswork, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.GoForTheEyes, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.GunkUp, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.Hailstorm, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.HelixDrill, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Hologram, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.Hotfix, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.Hyperbeam, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.IceLance, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Iteration, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Leap, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.LightningRod, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.Loop, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.MachineLearning, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.MeteorStrike, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Modded, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.MomentumStrike, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.MultiCast, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Null, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Overclock, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Quadcast, CharacterOptions.Defect, CardRarity.Ancient),
        new(CardOptions.Rainbow, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Reboot, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Refract, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.RocketPunch, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Scavenge, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Scrape, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.ShadowShield, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Shatter, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.SignalBoost, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Skim, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Smokestack, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Spinner, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Storm, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.StrikeDefect, CharacterOptions.Defect, CardRarity.Basic),
        new(CardOptions.Subroutine, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Sunder, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Supercritical, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.SweepingBeam, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.Synchronize, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Synthesis, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Tempest, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.TeslaCoil, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Thunder, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.TrashToTreasure, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.Turbo, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.Uproar, CharacterOptions.Defect, CardRarity.Common),
        new(CardOptions.Voltaic, CharacterOptions.Defect, CardRarity.Rare),
        new(CardOptions.WhiteNoise, CharacterOptions.Defect, CardRarity.Uncommon),
        new(CardOptions.Zap, CharacterOptions.Defect, CardRarity.Basic),

        #endregion

        #region Colorless pool

        new(CardOptions.Alchemize, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.Anointed, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.Automation, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.BeatDown, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.Bolas, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.Calamity, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.Catastrophe, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.DarkShackles, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Discovery, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.DramaticEntrance, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Entropy, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.Equilibrium, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.EternalArmor, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.Fasten, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Finesse, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Fisticuffs, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.FlashOfSteel, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.GoldAxe, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.HandOfGreed, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.HiddenGem, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.Impatience, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.JackOfAllTrades, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Jackpot, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.MasterOfStrategy, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.Mayhem, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.MindBlast, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Nostalgia, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.Omnislice, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Panache, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.PanicButton, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.PrepTime, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Production, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Prolong, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Prowess, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Purity, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Rend, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.Restlessness, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.RollingBoulder, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.Salvo, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.Scrawl, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.SecretTechnique, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.SecretWeapon, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.SeekerStrike, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Shockwave, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Splash, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Stratagem, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.TheBomb, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.TheGambit, CharacterOptions.Any, CardRarity.Rare),
        new(CardOptions.ThinkingAhead, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.ThrummingHatchet, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.UltimateDefend, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.UltimateStrike, CharacterOptions.Any, CardRarity.Uncommon),
        new(CardOptions.Volley, CharacterOptions.Any, CardRarity.Uncommon)

        #endregion
    ];
    
    // Includes basics and Ancient cards
    public static readonly ImmutableDictionary<CharacterOptions, ImmutableArray<CardDefinition>>
        EntireCardPools =
            AllCardDefinitions
                .GroupBy(c => c.Character)
                .ToImmutableDictionary(
                    g => g.Key,
                    g => g.Select(x => x).ToImmutableArray());
    
    // Cards that can actually be obtained via transforms or card rewards
    public static readonly ImmutableDictionary<CharacterOptions, ImmutableArray<CardDefinition>>
        AvailableCardDefinitionPools =
            AllCardDefinitions
                .Where(c => c.Rarity.In([CardRarity.Common, CardRarity.Uncommon, CardRarity.Rare]))
                .GroupBy(c => c.Character)
                .ToImmutableDictionary(
                    g => g.Key,
                    g => g.Select(x => x).ToImmutableArray());
    
    // Cards that can actually be obtained via transforms or card rewards
    public static readonly ImmutableDictionary<CharacterOptions, ImmutableArray<CardOptions>>
        AvailableCardPools =
            AllCardDefinitions
                .Where(c => c.Rarity.In([CardRarity.Common, CardRarity.Uncommon, CardRarity.Rare]))
                .GroupBy(c => c.Character)
                .ToImmutableDictionary(
                    g => g.Key,
                    g => g.Select(x => x.Card).ToImmutableArray());
    
    public static readonly ImmutableDictionary<CharacterOptions, ImmutableArray<CardOptions>>
        RareCardPools =
            AllCardDefinitions.Where(c => c.Rarity == CardRarity.Rare)
                .GroupBy(c => c.Character)
                .ToImmutableDictionary(
                    g => g.Key,
                    g => g.Select(x => x.Card).ToImmutableArray());
}